In [1]:
import numpy as np

# Ejemplo de uso
data = [13, 32, 33]
row = [0, 1, 2]
col = [0, 1, 2]
shape = (3, 3)

In [2]:
class COO:
    def __init__(self, data, row, col, shape):
        self.data = np.array(data)
        self.row = np.array(row)
        self.col = np.array(col)
        self.shape = shape

    def to_dense(self):
        dense_matrix = np.zeros(self.shape)
        for d, r, c in zip(self.data, self.row, self.col):
            dense_matrix[r, c] = d
        return dense_matrix

    def __repr__(self):
        result = []
        for r, c, d in zip(self.row, self.col, self.data):
            result.append(f"  ({r}, {c})\t{d}")
        return "\n".join(result)

coo_matrix = COO(data, row, col, shape)
print("Matriz dispersa en formato COO:")
print(coo_matrix)
print("Matriz densa convertida desde COO:")
print(coo_matrix.to_dense())

Matriz dispersa en formato COO:
  (0, 0)	13
  (1, 1)	32
  (2, 2)	33
Matriz densa convertida desde COO:
[[13.  0.  0.]
 [ 0. 32.  0.]
 [ 0.  0. 33.]]


In [4]:
from scipy.sparse import coo_matrix

# Crear la matriz dispersa usando scipy
scipy_coo = coo_matrix((data, (row, col)), shape=shape)

print("Matriz dispersa en formato COO usando scipy:")
print(scipy_coo)
print("Matriz densa convertida desde scipy COO:")
print(scipy_coo.toarray())

Matriz dispersa en formato COO usando scipy:
<COOrdinate sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	13
  (1, 1)	32
  (2, 2)	33
Matriz densa convertida desde scipy COO:
[[13  0  0]
 [ 0 32  0]
 [ 0  0 33]]


In [5]:
# Comparación
coo_matrix = COO(data, row, col, shape)
dense_from_custom = coo_matrix.to_dense()
dense_from_scipy = scipy_coo.toarray()

print("Matriz densa desde COO:")
print(dense_from_custom)
print("Matriz densa desde scipy COO:")
print(dense_from_scipy)

print("¿Son iguales las matrices densas?")
print(np.array_equal(dense_from_custom, dense_from_scipy))

Matriz densa desde COO:
[[13.  0.  0.]
 [ 0. 32.  0.]
 [ 0.  0. 33.]]
Matriz densa desde scipy COO:
[[13  0  0]
 [ 0 32  0]
 [ 0  0 33]]
¿Son iguales las matrices densas?
True
